<?php

$form = $this->contactForm;
$form->prepare();
?>

<div>
    <h1>Contact Form</h1>
    <?php echo $this->form()->openTag($form); ?>
    <div class="field-wrap">
        <label>
            Name<span class="req">*</span>
        </label>
        <?php echo $this->formInput($form->get('name')); ?>
        <?php echo $this->formElementErrors($form->get('name')); ?>

    </div>
    
    <div class="field-wrap">
        <label>
            Contact Number<span class="req">*</span>
        </label>
        <?php echo $this->formInput($form->get('contactno')); ?>
        <?php echo $this->formElementErrors($form->get('contactno')); ?>

    </div>
    
    <div class="field-wrap">
        <label>
            Email<span class="req">*</span>
        </label>
        <?php echo $this->formInput($form->get('email')); ?>
        <?php echo $this->formElementErrors($form->get('email')); ?>
    </div>
    
    <div class="field-wrap">
        <label>
            Post<span class="req">*</span>
        </label>
        <?php echo $this->formSelect($form->get('post')); ?>
        <?php echo $this->formElementErrors($form->get('post')); ?>
    </div>
    
    <button class="button button-block" type="submit">Submit</button>
    
    <?php echo $this->form()->closeTag(); ?>
</div>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
<script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
    $("#contact").validate({
    
        // Specify the validation rules
        rules: {
            name: {
                required : true,
            },
            contactno:{
              required : true, 
                number : true,
            },
//            categoryimage: {
//                    extension: "jpg|png|jpeg|gif"
//                },
//            gender: "required",
//            address: "required",
//            email: {
//                required: true,
//                email: true
//            },
//            username: "required",
//            password: {
//                required: true,
//                minlength: 5
//            }
        },
        
        // Specify the validation error messages
        messages: {
            name: {
                required: "Please enter your name"
            },
            contactno : {
                required : "please enter number",
                number : "enter number only"
            }
//            categoryimage: {
//                    extension: "Please upload only jpg, png, jpeg or gif image"
//                }
//            gender: "Please specify your gender",
//            address: "Please enter your address",
//            email: "Please enter a valid email address",
//            username: "Please enter a valid username",
//            password: {
//                required: "Please provide a password",
//                minlength: "Your password must be at least 5 characters long"
//            }
        },
        
        submitHandler: function(form) {
            form.submit();
        }
    });

});    
</script>