<?php
$form = $this->loginForm;
$form->prepare();
?>

<div id="login">   
    <h1>Login</h1>

    <?php echo $this->form()->openTag($form); ?>

    <div class="field-wrap">
        <label>
            Email Address<span class="req">*</span>
        </label>
        <?php echo $this->formInput($form->get('email')); ?>
        <?php echo $this->formElementErrors($form->get('email')); ?>

    </div>

    <div class="field-wrap">
        <label>
            Password<span class="req">*</span>
        </label>
        <?php echo $this->formInput($form->get('password')); ?>
        <?php echo $this->formElementErrors($form->get('password')); ?>
    </div>


    <p class="forgot"><a href="<?php echo $this->url('home', array('action' => 'register')); ?>">Register</a></p>

    <button class="button button-block" type="submit">Login</button> 

    <?php echo $this->form()->closeTag(); ?>

</div>


